
name = "prophetic-intelligence-backend"
main = "worker.js"
compatibility_date = "2025-08-09"

[[d1_databases]]
binding = "DB"
database_name = "prophecy"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[[kv_namespaces]]
binding = "KV"
id = "REPLACE_WITH_YOUR_KV_ID"
